#!/usr/bin/env python3
"""Generate BENCHMARK_REPORT.md from a campaign directory.

Requirements: BEN-019, VNV-021, VNV-024, section 8.1.

Rules enforced here rather than left to the author:
  * no mean is printed without median, P95 and worst case beside it (BEN-016);
  * a missed detection prints as a dash, never as a zero (section 8.1);
  * the configuration, commit, compiler and seed base that produced the numbers
    are printed with them, so a figure cannot be quoted without its provenance
    (VNV-021).

Usage:
  tools/report/build_report.py results/campaign [--sweep results/drift_sweep]
                               [--out BENCHMARK_REPORT.md]
"""
import argparse
import json
import os
import statistics
import sys

ESTIMATOR_LABELS = {
    "gnss_only": "GNSS only",
    "ins_dr": "INS dead reckoning",
    "ekf": "EKF (no integrity)",
    "integrity_ekf": "EKF + innovation gating",
    "solsep_ekf": "EKF + solution separation",
}
ORDER = list(ESTIMATOR_LABELS)


def fmt(value, digits=2, dash_below=0):
    if value is None:
        return "—"
    if isinstance(value, float) and value < dash_below:
        return "—"
    return f"{value:.{digits}f}"


def load(campaign):
    manifest_path = os.path.join(campaign, "manifest.json")
    runs_path = os.path.join(campaign, "runs.jsonl")
    if not os.path.exists(manifest_path):
        sys.exit(f"error: {manifest_path} not found. Run aerolab_bench first.")
    manifest = json.load(open(manifest_path, encoding="utf-8"))
    runs = []
    if os.path.exists(runs_path):
        with open(runs_path, encoding="utf-8") as f:
            runs = [json.loads(line) for line in f if line.strip()]
    return manifest, runs


def group(runs):
    cells = {}
    for r in runs:
        cells.setdefault((r["scenario"], r["estimator"]), []).append(r)
    return cells


def scenario_table(cells, scenario):
    lines = [
        "| Architecture | RMSE median | RMSE P95 | worst | detect | isolate | TTD median | avail | continuity |",
        "| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    for est in ORDER:
        runs = cells.get((scenario, est))
        if not runs:
            continue
        rmse = sorted(r["rmse_m"] for r in runs)
        worst = max(r["max_m"] for r in runs)
        faulted = [r for r in runs if r["fault_detected"] is not None]
        detected = [r for r in runs if r["fault_detected"]]
        isolated = [r for r in runs if r["fault_isolated"]]
        ttds = sorted(r["ttd_s"] for r in runs if r["ttd_s"] is not None)
        avail = statistics.mean(r["availability"] for r in runs)
        continuity = statistics.mean(r["continuity"] for r in runs)
        n = len(runs)
        p95 = rmse[max(0, int(0.95 * n) - 1)]
        lines.append(
            "| {label} | {med} | {p95} | {worst} | {det} | {iso} | {ttd} | {avail} | {cont} |".format(
                label=ESTIMATOR_LABELS.get(est, est),
                med=fmt(statistics.median(rmse)),
                p95=fmt(p95),
                worst=fmt(worst),
                det=f"{100.0 * len(detected) / n:.0f} %" if faulted else "—",
                iso=f"{100.0 * len(isolated) / n:.0f} %" if faulted else "—",
                ttd=fmt(statistics.median(ttds)) if ttds else "—",
                avail=f"{100.0 * avail:.1f} %",
                cont=f"{100.0 * continuity:.0f} %",
            )
        )
    return "\n".join(lines)


def sweep_section(sweep_dir):
    path = os.path.join(sweep_dir, "sweep.json")
    if not os.path.exists(path):
        return None
    data = json.load(open(path, encoding="utf-8"))
    lines = [
        "| drift rate | total offset | gating: detect | gating: TTD | separation: detect | separation: TTD |",
        "| ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    for point in data["points"]:
        gate = point.get("integrity_ekf", {})
        sep = point.get("solsep_ekf", {})
        lines.append(
            "| {rate} m/s | {offset} m | {gd} | {gt} | {sd} | {st} |".format(
                rate=fmt(point["rate"], 2),
                offset=fmt(point["offset_m"], 0),
                gd=f"{100.0 * gate.get('detection_rate', 0):.0f} %",
                gt=fmt(gate.get("ttd_median")),
                sd=f"{100.0 * sep.get('detection_rate', 0):.0f} %",
                st=fmt(sep.get("ttd_median")),
            )
        )
    return data["seeds_per_point"], "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("campaign")
    parser.add_argument("--sweep", default=None)
    parser.add_argument("--out", default="BENCHMARK_REPORT.md")
    args = parser.parse_args()

    manifest, runs = load(args.campaign)
    cells = group(runs)
    scenarios = sorted({s for s, _ in cells})

    out = []
    out.append("# Benchmark report\n")
    out.append(
        "Generated by `tools/report/build_report.py`. Every figure below comes from the "
        "campaign identified in the provenance block; none of them is typed in by hand.\n"
    )

    out.append("\n## Provenance\n")
    out.append("| | |")
    out.append("| --- | --- |")
    for key, label in [
        ("suite", "Suite"),
        ("config", "Configuration"),
        ("commit", "Commit"),
        ("version", "Version"),
        ("build_type", "Build type"),
        ("compiler", "Compiler"),
        ("threads", "Worker threads"),
        ("total_runs", "Total runs"),
        ("seed_base", "Seed base"),
        ("verdict_failures", "Runs failing their acceptance block"),
    ]:
        if key in manifest:
            out.append(f"| {label} | `{manifest[key]}` |")

    policy = manifest.get("trace_policy", {})
    if policy:
        out.append(
            f"\n**Trace retention.** Full telemetry was kept for the first "
            f"{policy.get('keep_first_n')} seeds of each scenario and for every failed run. "
            f"Aggregate metrics below cover **every** run in the campaign; nothing was sampled "
            f"away from the statistics (DEV-008).\n"
        )

    out.append("\n## How to read these tables\n")
    out.append(
        "- No mean appears without its median, P95 and worst case (BEN-016).\n"
        "- A dash in time-to-detect means **no detection was raised**. It is never printed as "
        "zero: averaging a missed detection as an instant response is the easiest way to publish "
        "a flattering benchmark.\n"
        "- Availability counts LOW_CONFIDENCE and UNSAFE as unavailable. Refusing to answer is "
        "better than answering wrongly, but it is still an outage.\n"
        "- Continuity is binary per run and reported as the fraction of runs with no unscheduled "
        "interruption.\n"
    )

    if args.sweep:
        result = sweep_section(args.sweep)
        if result:
            seeds, table = result
            out.append("\n## Detectability floor against drift rate\n")
            out.append(
                "The headline experiment. Each row injects a satellite position ramp at a "
                "different rate over the same 45 s window, with the same seed set, and reports "
                f"how often each policy noticed. {seeds} seeds per point.\n"
            )
            out.append(table)
            out.append(
                "\nThe question this answers is not whether the integrity layer works — a 100 m "
                "step is caught by anything — but how slowly a source has to lie before each "
                "policy stops noticing.\n"
            )

    out.append("\n## Per-scenario results\n")
    for scenario in scenarios:
        out.append(f"\n### {scenario}\n")
        out.append(scenario_table(cells, scenario))

    out.append("\n## Reproducing this\n")
    out.append("```bash")
    out.append("cmake --preset release && cmake --build build/release -j")
    out.append(
        f"./build/release/bin/aerolab_bench --suite benchmark/core.yaml "
        f"--out {args.campaign} --jobs $(nproc)"
    )
    if args.sweep:
        out.append(f"bash tools/analysis/drift_sweep.sh 150 {args.sweep}")
    out.append(f"python3 tools/report/build_report.py {args.campaign}" +
               (f" --sweep {args.sweep}" if args.sweep else ""))
    out.append("```")
    out.append(
        "\nThe evaluation configuration is frozen. Any change to `configs/evaluation.json` "
        "invalidates every number above and must be recorded in `CHANGELOG.md` before the next "
        "campaign (section 8.1).\n"
    )

    text = "\n".join(out) + "\n"
    with open(args.out, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print(f"wrote {args.out}: {len(scenarios)} scenarios, {len(runs)} run records")


if __name__ == "__main__":
    main()
